### ISSUE TITLE
Connection errors leads frigate to fail

### ISSUE THREAD

**Issue by thundergreen** [jakowenko/double-take#12]
I am not 100% sure but i face an issue since using this APP

https://github.com/blakeblackshear/frigate/discussions/853

you might have a look at this? I think it's related with snapshots and connection not properly closed. I am not a progrmmer but since i installed you app this issue occurs :(

**Comment by jakowenko** [comment]
I have see this a few times on my local setup, but since the error resides on the Frigate side, there's not a lot I can do. I haven't had any Frigate crashes though for the last few days and when one does occur `docker restart frigate` resolves the issue.

Double Take does add up to a `0 - 1` second delay before each Frigate API request, to help reduce hitting the API simultaneously.

I've also updated the README to include a section and link to the current [Github](https://github.com/jakowenko/double-take#known-issues) issue for Frigate.

Feel free to reopen this issue if you feel this is something on the Double Take side and have a way to reproduce it.
