### ISSUE TITLE
[FEAT] Documentation for adding image to picture card

### ISSUE THREAD

**Issue by jonwilliams84** [jakowenko/double-take#120]
I am trying to add the last image to a picture-element card using the following as an example:

```
http://double-take.jetson.local/api/storage/matches/{{states.sensor.double_take_unknown.attributes.unknown.filename}}?box=true
```

In developer tools and templates, this renders the url correctly as:

http://double-take.jetson.local/api/storage/matches/670f03f6-7d88-49ba-be61-66789f6fa554.jpg?box=true

However the picture doesn't show in a card.

What am I missing? 

If set this as a camera in HA config it works but surely there is an easier way to do it?

```
  - platform: generic
    still_image_url: http://double-take.jetson.local/api/storage/matches/{{states.sensor.double_take_unknown.attributes.unknown.filename}}?box=true
    name: UnknownFaces
```

Regards,

Jon

**Comment by jakowenko** [comment]
@tkdrob, if you want to message me on Discord, I can get a logo created for you with the name in it.

@jonwilliams84, I'm going to close this since it's included in `v1.4.0`. There is a small fix coming in `v1.4.1` which will be out in a few hours.

Feel free to reopen if you run into issues with it.
