### ISSUE TITLE
Ability to delete Person

### ISSUE THREAD

**Issue by Haloooch** [jakowenko/double-take#66]
Currently you can add a new person, but I don't think there is a way to delete a user. 

I originally set the names as 'firstname lastname' the space caused some problem in HA, as a result I recreated them as 'firstname_lastname' but I don't seem to be able to delete the original names. While you could force _ where there are blank names I think the ability to delete would be more valuable.

**Comment by jakowenko** [comment]
I can work on getting this added in and try to better handle names with spaces in them. In the meantime, you can delete that folder from your host machine. Deleting `./storage/train/FOLDER NAME` should remove it from the dropdown.

**Comment by jakowenko** [comment]
Hey @Haloooch, I just pushed a new beta build that should resolve both of these issues. When all the images are untrained for a user, the button will change to "Remove". This will then allow you to delete that folder and any images within it.

<img width="420" alt="Screen Shot 2021-08-01 at 11 02 45 PM" src="https://user-images.githubusercontent.com/1081811/127799030-a19f9340-7eb7-4296-af04-4935653d2edc.png">
<img width="340" alt="Screen Shot 2021-08-01 at 11 02 51 PM" src="https://user-images.githubusercontent.com/1081811/127799039-3c385d9a-6c06-4357-bab9-0b3e5fb98f80.png">

I also updated the MQTT publishing to HA to replace the spaces with a `_` for the entity name. I was able to test this locally and verify it worked.

Let me know if this works for you!

**Comment by Haloooch** [comment]
Very cool, thank you! Life is getting in the way of HA at the moment, so suspect I will not be able to try the new beta till later in the week. If I do experience any issues I will let you know.

**Comment by kanemari** [comment]
just adding to this one. I have tried deleting trained faces, but it doesnt seem to remove them from the database. I have even gone to the point of deleting the database, manually removing the all training directory 'names' and manually adding all training images apart from the one I wanted removed back again, but it still detects the deleted face in images.

e.g. started with 3 faces - joe, peter, nick. deleted all folders under /train, deleted database.db, added images for joe and peter back into double-take, but nick is still detected in images despite there being no directory for him under /train, and the databse being created new.

do images get saved within compreface? there doesnt seem to be any option to remove trained images from there in the UI.

**Comment by jakowenko** [comment]
Hey @kanemari, untraining from Double Take to CompreFace only happens when you use the UI / API. Once the image is trained, some of that information resides in CompreFace. So just deleting the files / database on the Double Take side won't do anything.

Here's what I would do if you want to start fresh.
- Create a new API Key in CompreFace and only handle training / untraining from the Double Take UI.
- Or add new images for the users you had above to Double Take. Click the "sync" button which should untrain that user from CompreFace then retrain it with just the images you have in the training folder.
- Or use the Double Take API directly for removing users who don't exist in Double Take anymore but reside in your detectors. You can use the [`api/train/remove/:name`](https://documenter.getpostman.com/view/1013188/TzsWuAa8#b5a2ea7e-74bc-4456-bdc7-be7bf554f544) endpoint to manually remove those users.

Let me know if this makes sense and helps fix your issue.

![Screen Shot 2021-09-03 at 10 50 31 AM](https://user-images.githubusercontent.com/1081811/132025415-5932a4ae-bb5e-4d0f-9f64-cf9875ed5a72.png)

**Comment by kanemari** [comment]
I did use the UI at first, but it left the folder behind in /train and still detected them in the images even though their name wasnt listed in the UI anymore. anyway, have created a new recognition service in compreface and retrained the images / faces I want to keep. hopefully that will do it.

**Comment by jakowenko** [comment]
Try doing it again with the newest beta image. I caught a bug last night in regards to the training page and just the untraining of CompreFace photos where it didn't realize a trained one was actually trained.

**Comment by kanemari** [comment]
seems to be working now, thanks!
