### ISSUE TITLE
Need to configure cameras?

### ISSUE THREAD

**Issue by TheQue42** [jakowenko/double-take#72]
Hi, 

Sorry if I am thick, but I am a bit confuzed whether all cameras are auto-detected, since my first try at double-take, it seems it only fokuses on two of my four cameras in frigate.

The image in the README.md has a yaml-config example that also configures custom url and topic values for the cameras, but "how needed" this is, or when to use it, is not fully clear.

Somewhat related to the fact that I havent fully understood where the snapshots provided at frigats http url, are the same (size-wise, etc) with the ones sent via mqtt.

**Comment by jakowenko** [comment]
Hey there, thanks for checking out this project.

By default, if you want to watch for all cameras from Frigate you can just include this.
```yaml
frigate:
  url: http://frigate-url.com:5000
```

You don't need to configure anything that is a default, I include some samples in the README to show what's can be changed, but I don't do it on my personal setup, I usually just leave the defaults.

There's two Frigate snapshot images, one that can be accessed via the Frigate API `snapshot.jpg`, though using this image causes Frigate to crash if running v0.8, which is why it's set to `0` by default. The second snapshot image is from the MQTT topic. The latest.jpg and snapshot.jpg images sizes can be configured via Double Take, but the MQTT one needs to be configured in the Frigate config.yml.

Mine looks something like this
```yaml
cameras:
  front-door:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
```

**Comment by TheQue42** [comment]
Hi, and thanks for a quick reply (and nice software :-) )

Frigate is configured, and the mqtt-snapshot config, and it seems to be working somewhat ok. But in HA, i've only found sensor.double-take_livingroom, and sensor.double-take_kitchen, but even though I've been making faces to my "front door" camera, (and got frigate clips recorded), I dont have a sensor.double-take_front_door value in HA.

It seems like the mqtt-sensors are not fully created towards HA until something is fully detected(several times?), and thats where I seem to have issues. Faces in snapshots are so small so facebox has real problems detecting anything unless I shove my face RIGHT UP to the camera :-) 

It would be nice if I could "push/force" the creation of all available sensors for all cameras and trained-faces, towards HA, even though they just contain some temporary value. Then I could make automations for them, before hand, even if my wife hasnt actually been matched yet.

**Comment by TheQue42** [comment]
Is there a way to increase debug-level?

I just came home, was identified as my wife, but there is still no sensor in home-assistant, known as sensor.double_take_rebecca, only sensor.double_take_taisto.

The mqtt log on the HA side at that time, only shows:

`2021-08-19 15:38:39 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/double-take/front_door/state: b'{"id":"15d50ba3-6277-41a2-8c6f-297df5e1da83","duration":0.18,"timestamp":"2021-08-19T13:38:09.753Z","attempts":1,"camera":"front_door","zones":[],"matches":[],"personCount":0}'
`

**Comment by jakowenko** [comment]
I will include more logging levels in future releases. I do have support for it, but I need to add the logs to the various parts of the code.

Closing this issue for now. Feel free to open a new one if you still experience issues.
