### ISSUE TITLE
Get registered persons from DeepStack

### ISSUE THREAD

**Issue by MrksHfmn** [jakowenko/double-take#77]
Hi! Is it possible to use the trained persons from DeepStack in Double Take? I registered the persons and faces over API in DeepStack. Can I somehow retrieve the information in Double Take?

**Comment by jakowenko** [comment]
The images you trained into DeepStack will still be used with Double Take when images are processed. I know DeepStack's API allows you to pull the names of the registered faces, but not the images used to train them, so it would probably be hard to just integrate it right into the current Train page since not all of the data is available.

If you didn't train a lot of images, it might just be easier to remove them and retrain it from the Double Take UI to make managing it easier in the future.

**Comment by MrksHfmn** [comment]
Thank you for your reply! I already did some training, but it doesn't matter ... I can only upload one image at a time in the browser. Maybe you could allow more here?

Can I copy all my images from the peson to ./.storage/train/${name} and run the training on the web UI?

**Comment by jakowenko** [comment]
FYI, just pushed an update to the beta build that should allow you to upload multiple images now at once.

**Comment by jakowenko** [comment]
Closing as this was merged into release `1.0.0`
