### ISSUE TITLE
Enhancement: Increase width of name field

### ISSUE THREAD

**Issue by mr-manuel** [jakowenko/double-take#87]
Could you please increase the width of the name field or make it responsive so that it takes the half width of the column? If you have first and lastname they unfortunately won't fit.

https://github.com/jakowenko/double-take/blob/0e1df101ddc0ffaa188a4410c2923e2e60f43f0f/frontend/src/components/Header.vue#L429

**Comment by jakowenko** [comment]
Hey @mr-manuel, I increased the width of both the dropdown and text box on desktop and mobile.

I don't want it to span half the page because it would look a little strange and I want to make sure there's room for the other buttons in the toolbar to fit within a single row.

Hopefully this new size works better for you!

**Comment by mr-manuel** [comment]
Yes, thank you!
